[theme]
primaryColor = "#FF8C42"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFD699"
textColor = "#FF8C42"
font = "monospace"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
port = 8502
headless = true
